/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false --env-interface=HubEnv` (hash: ef46036fc8fda430198bc5d575c620a6)
interface __BaseEnv_HubEnv {
	WORKFLOWS_HUB: KVNamespace;
	HUB_COUNTERS: DurableObjectNamespace<import("./src/index").HubCounter>;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/index");
		durableNamespaces: "HubCounter";
	}
	interface Env extends __BaseEnv_HubEnv {}
}
interface HubEnv extends __BaseEnv_HubEnv {}
